sudo: required

services:
  - docker

language: python
python:
  - "3.4"

before_script:
  - docker-compose run main true
  - ./puffin.py db create
  - ./puffin.py db upgrade

install: "pip install -r requirements-dev.txt"

script: py.test
 
