sudo: required

git:
    submodules: false

services:
  - docker

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init
    - sed -i 's/git@github.com:/https:\/\/github.com\//' apps/.gitmodules
    - git submodule update --init --recursive
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine

script:
    - docker-compose run puffin test
