sudo: required

services:
  - docker

language: python
python:
  - "3.4"

install: "pip install -r requirements-dev.txt"

before_script:
  - docker-compose run deps
  - sleep 5
  - ./puffin.py db create
  - ./puffin.py db upgrade

script: py.test
 
