sudo: required

services:
  - docker

language: python
python:
  - "3.4"

before_install:
    - sudo apt-get upgrade docker-engine

install: "pip install -r requirements-dev.txt"

before_script:
  - docker-compose -f docker-compose-deps.yml up -d

script: py.test
 
