sudo: required

services:
  - docker

language: python
python:
  - "3.4"

before_install:
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine

install: "pip install -r requirements-dev.txt"

before_script:
  - docker-compose -f docker-compose.yml up -d
  - docker stop puffin_main_1

script: py.test
 
