version: '2'

services:

    main:
        build: .
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - db
        ports: 
            - "8080"
        command: 
            - "db create"
            - "db upgrade"
            - "user create puffin"
            - "machine network" 
            - "machine proxy"
            - "machine mail"
            - "machine dns"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=puffin
            - MAIL_SERVER=mailhog
            - MAIL_PORT=1025

    db:
        image: postgres
        ports:
            - "15432:5432"

