version: '2'

services:

    main:
        extends:
            file: docker-compose-common.yml
            service: puffin
        depends_on:
            - db
        command: 
            - "db create"
            - "db upgrade"
            - "user create puffin"
            - "machine network" 
            - "machine proxy"
            - "machine mail"
            - "machine dns"

    db:
        extends:
            file: docker-compose-common.yml
            service: db
        ports:
            - "15432:5432"

