main:
    extends:
        file: docker-compose-common.yml
        service: puffin
    links:
        - db
        - mail
    command: [""]

db:
    extends:
        file: docker-compose-common.yml
        service: db
    ports:
        - "15432:5432"

mail:
    extends:
        file: docker-compose-common.yml
        service: mail

