main:
    extends:
        file: docker-compose-common.yml
        service: puffin
    links:
        - db
    environment:
        - SERVER_NAME
        - SECURITY_REGISTERABLE=false
        - MAIL_SUPPRESS_SEND=true

db:
    extends:
        file: docker-compose-common.yml
        service: db

