version: '2'

services:

    main:
        build: .
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - db
        ports: 
            - "8080"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=puffin
            - SERVER_NAME=localhost
            - VIRTUAL_HOST=localhost
            - SECRET_KEY=puffin
            - MAIL_SERVER=<smtp-server>
            - MAIL_PORT=<smtp-port>
            - MAIL_USERNAME=<smtp-login>
            - MAIL_PASSWORD=<smtp-password>
            - MAIL_DEFAULT_SENDER=Puffin <sender-address>
            - MAIL_USE_TLS=False
            - MAIL_USE_SSL=False

    db:
        image: postgres
        ports:
             - "5432"



