version: '2'

services:

    puffin:
        build: .
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=puffin
            - MAIL_SERVER=mail
            - MAIL_PORT=1025
        ports: 
            - "8080"

    db:
        image: postgres
        ports:
             - "5432"

    mail:
        image: mailhog/mailhog
        ports: 
            - "1025:1025"
            - "8025:8025"


