version: '2'

services:

    main:
        extends:
            file: docker-compose-common.yml
            service: puffin
        depends_on:
            - db
            - mail
        command: 
            - "db create"
            - "db upgrade"
            - "user create puffin"
            - "machine network" 
            - "machine proxy"
            - "machine dns"
            - "server"
        ports: 
            - "8080:8080"
    
    db:
        extends:
            file: docker-compose-common.yml
            service: db
        ports:
            - "15432:5432"

    mail:
        extends:
            file: docker-compose-common.yml
            service: mail

