version: '2'

services:

    puffin:
        build: .
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=puffin
        ports: 
            - "8080"

    db:
        image: postgres
        ports:
             - "5432"


