version: '2'

services:

    main:
        build: .
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - db
        ports: 
            - "8080"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=puffin
            - SERVER_NAME=localhost
            - VIRTUAL_HOST=localhost
            - SECRET_KEY=puffin
            - SECURITY_REGISTERABLE=false
            - MAIL_SUPPRESS_SEND=true

    db:
        image: postgres
        ports:
             - "5432"

