main:
    extends:
        file: docker-compose-common.yml
        service: puffin
    links:
        - db
        - mail
    ports: 
        - "8080:8080"

db:
    extends:
        file: docker-compose-common.yml
        service: db
    ports:
        - "15432:5432"

mail:
    extends:
        file: docker-compose-common.yml
        service: mail
    ports: 
        - "1025:1025"
        - "8025:8025"

