main:
    extends:
        file: docker-compose-common.yml
        service: puffin
    links:
        - db
        - mail
    command: []

db:
    extends:
        file: docker-compose-common.yml
        service: db

mail:
    extends:
        file: docker-compose-common.yml
        service: mail

