version: '2'

services:

    main:
        build: .
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - db
            - dns
            - mailhog
        ports: 
            - "8080:8080"
        command: 
            - "db create"
            - "db upgrade"
            - "user create puffin"
            - "machine proxy"
            - "machine mail"
            - "machine dns"
            - "server"
        environment:
            - MAIL_SERVER=mailhog
            - MAIL_PORT=1025
        networks:
            - front
            - back
            - default
    
    db:
        image: postgres
        ports:
            - 5432
        networks:
            back:
                aliases:
                    - db
    
    dns:
        image: loomchild/dns
        ports: 
            - 53:53/udp
        networks:
            back:
                aliases:
                    - dns

    dnsfix:
        image: sequenceiq/alpine-dig
        entrypoint: ["/bin/sh", "-c", "echo nameserver `dig +short dns` > /etc/resolv.conf"]
        network_mode: "service:main"

    mailhog:
        image: mailhog/mailhog
        ports: 
            - "8025:8025"
            - 1025
        networks:
            front:
            back:
                aliases:
                    - mailhog

networks:
    
    front:
    back:
