version: '2'

services:

    main:
        image: mailhog/mailhog
        ports: 
            - 8025
            - 1025
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=8025
        networks:
            front:
            back:
                aliases:
                    - mailhog

networks:
    front:
        external: 
            name: "network_front"
    back:
        external:
            name: "network_back"

