version: '2'

services:

    main:
        image: jwilder/nginx-proxy
        volumes: 
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "80:80"
        network_mode: "bridge"

