version: '2'

services:

    main:
        image: loomchild/gogs
        ports: 
            - 3000
        volumes: 
            - main_data:/data
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
        network_mode: "bridge"

volumes:
    main_data:
