version: '2'

services:

    main:
        image: owncloud:latest
        ports: 
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        network_mode: "bridge"

volumes:
    main_data:
