main:
    image: owncloud:latest
    ports: 
        - 80
    volumes_from: 
        - main_data
    environment:
        - VIRTUAL_HOST
        - VIRTUAL_PORT=80

main_data:
    image: tianon/true
    volumes:
        - /var/www/html
