version: '2'

services:

    main:
        image: owncloud:latest
        ports: 
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        networks:
            - front
            - default

volumes:
    main_data:

networks:
    front:
        external:
            name: "network_front"
