version: '2'

services:

    main:
        image: owncloud:latest
        ports: 
            - 80
        volumes_from: 
            - main_data
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        network_mode: "bridge"

    main_data:
        image: tianon/true
        volumes:
            - /var/www/html
