version: '2'

services:

    main:
        image: loomchild/dns
        ports: 
            - 53:53/udp
        networks:
            back:

networks:
    back:
        external:
            name: "network_back"

