main:
    image: loomchild/ghost
    ports: 
        - 2368
    volumes_from: 
        - main_data
    environment:
        - VIRTUAL_HOST
        - VIRTUAL_PORT=2368

main_data:
    image: tianon/true
    volumes:
        - /var/lib/ghost
    
