version: '2'

services:
 
    main:
        image: loomchild/ghost
        ports: 
            - 2368
        volumes: 
            - main_data:/var/lib/ghost
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=2368
        network_mode: "bridge"

volumes:
    main_data:
