version: '2'

services:

    main:
        image: rocket.chat:latest
        links:
            - db
        ports:
            - 3000
        volumes: 
            - main_data:/app/uploads
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
        network_mode: "bridge"

    db:
        image: loomchild/mongo
        volumes: 
            - db_data_db:/data/db
            - db_data_configdb:/data/configdb
        network_mode: "bridge"

volumes:
    main_data:
    db_data_db:
    db_data_configdb:
