main:
    image: redmine:latest
    ports: 
        - 3000
    volumes_from: 
        - main_data
    environment:
        - VIRTUAL_HOST
        - VIRTUAL_PORT=3000

main_data:
    image: tianon/true
    volumes:
        - /usr/src/redmine/files
