version: '2'

services:

    main:
        image: redmine:latest
        ports: 
            - 3000
        volumes: 
            - main_data:/usr/src/redmine/files
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
        network_mode: "bridge"

volumes:
    main_data:
