version: '2'

services:

    main:
        image: redmine:latest
        ports: 
            - 3000
        volumes: 
            - main_data:/usr/src/redmine/files
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
        networks:
            - front
            - default

volumes:
    main_data:

networks:
    front:
        external:
            name: "puffin_front"
