version: '2'

services:
 
    main:
        image: loomchild/flarum
        links:
            - db
        ports: 
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        network_mode: "bridge"

    db:
        image: loomchild/mariadb
        ports: 
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: flarum
            MYSQL_USER: flarum
            MYSQL_PASSWORD: flarum
        volumes: 
            - db_data:/var/lib/mysql
        network_mode: "bridge"

volumes:
    main_data:
    db_data:
