version: '2'

services:

    main:
        image: wordpress
        links:
            - db:mysql
        ports:
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        network_mode: "bridge"
    
    db:
        image: loomchild/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes: 
            - db_data:/var/lib/mysql
        network_mode: "bridge"

volumes:
    main_data:
    db_data:
